"""Initial migration - clean schema

Revision ID: 999fc2a92e88
Revises: 
Create Date: 2025-05-11 16:52:38.468367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999fc2a92e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Allergy',
    sa.Column('AllergyCode', sa.String(length=20), nullable=False),
    sa.Column('AllergyName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('AllergyCode')
    )
    op.create_table('Bed',
    sa.Column('PatientRoomID', sa.Integer(), nullable=False),
    sa.Column('BedLabel', sa.Enum('A', 'B', name='bedlabel'), nullable=False),
    sa.Column('RoomNum', sa.String(length=10), nullable=False),
    sa.Column('Unit', sa.String(length=50), nullable=False),
    sa.Column('Wing', sa.Enum('BLUE', 'GREEN', name='wing'), nullable=False),
    sa.PrimaryKeyConstraint('PatientRoomID', 'BedLabel'),
    sa.UniqueConstraint('PatientRoomID', 'BedLabel', name='unique_bed_pk')
    )
    op.create_table('Clinic',
    sa.Column('ClinicID', sa.Integer(), nullable=False),
    sa.Column('ClinicName', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('ClinicID')
    )
    op.create_table('Illness',
    sa.Column('IllnessCode', sa.String(length=20), nullable=False),
    sa.Column('Description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('IllnessCode')
    )
    op.create_table('Medication',
    sa.Column('MedicationCode', sa.String(length=20), nullable=False),
    sa.Column('MedicationName', sa.String(length=100), nullable=False),
    sa.Column('QuantityOnOrder', sa.Integer(), nullable=True),
    sa.Column('QuantityOnHand', sa.Integer(), nullable=True),
    sa.Column('UnitCost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('YearToDateUsage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('MedicationCode')
    )
    op.create_table('OperatingRoom',
    sa.Column('OpRoomID', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('OpRoomID')
    )
    op.create_table('Owner',
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('Percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.CheckConstraint('Percentage >= 0 AND Percentage <= 100', name='check_owner_percentage'),
    sa.PrimaryKeyConstraint('OwnerID')
    )
    op.create_table('SurgeryType',
    sa.Column('SurgeryCode', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Category', sa.Enum('HOSPITALIZATION', 'OUTPATIENT', name='surgerycategory'), nullable=False),
    sa.Column('AnatomicalLocation', sa.String(length=100), nullable=True),
    sa.Column('SpecialNeeds', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('SurgeryCode')
    )
    op.create_table('ClinicPersonnel',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('Gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=False),
    sa.Column('Salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('SSN', sa.String(length=20), nullable=False),
    sa.Column('ClinicID', sa.Integer(), nullable=False),
    sa.CheckConstraint('Salary IS NULL OR (Salary >= 25000 AND Salary <= 300000)', name='check_salary_range'),
    sa.ForeignKeyConstraint(['ClinicID'], ['Clinic.ClinicID'], ),
    sa.PrimaryKeyConstraint('EmpID'),
    sa.UniqueConstraint('SSN')
    )
    op.create_table('DrugInteraction',
    sa.Column('Medication1', sa.String(length=20), nullable=False),
    sa.Column('Medication2', sa.String(length=20), nullable=False),
    sa.Column('Severity', sa.Enum('SEVERE', 'MODERATE', 'LITTLE', 'NONE', name='interactionseverity'), nullable=False),
    sa.ForeignKeyConstraint(['Medication1'], ['Medication.MedicationCode'], ),
    sa.ForeignKeyConstraint(['Medication2'], ['Medication.MedicationCode'], ),
    sa.PrimaryKeyConstraint('Medication1', 'Medication2')
    )
    op.create_table('MedicalCorporation',
    sa.Column('CorpName', sa.String(length=100), nullable=False),
    sa.Column('OwnerID', sa.Integer(), nullable=False),
    sa.Column('ClinicID', sa.Integer(), nullable=False),
    sa.Column('Percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('CorpHeadquarters', sa.String(length=255), nullable=False),
    sa.CheckConstraint('Percentage >= 0 AND Percentage <= 100', name='check_corp_percentage'),
    sa.ForeignKeyConstraint(['ClinicID'], ['Clinic.ClinicID'], ),
    sa.ForeignKeyConstraint(['OwnerID'], ['Owner.OwnerID'], ),
    sa.PrimaryKeyConstraint('CorpName', 'OwnerID', 'ClinicID')
    )
    op.create_table('SurgerySkill',
    sa.Column('SkillCode', sa.String(length=20), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('SurgeryCode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['SurgeryCode'], ['SurgeryType.SurgeryCode'], ),
    sa.PrimaryKeyConstraint('SkillCode')
    )
    op.create_table('Nurse',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('YearsOfExperience', sa.Integer(), nullable=True),
    sa.Column('Grade', sa.String(length=20), nullable=True),
    sa.Column('NursingUnits', sa.String(length=100), nullable=True),
    sa.Column('SurgeryTypeCode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['EmpID'], ['ClinicPersonnel.EmpID'], ),
    sa.ForeignKeyConstraint(['SurgeryTypeCode'], ['SurgeryType.SurgeryCode'], ),
    sa.PrimaryKeyConstraint('EmpID')
    )
    op.create_table('Physician',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('Percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Specialty', sa.String(length=100), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.Column('IsChief', sa.Boolean(), nullable=True),
    sa.Column('OwnerID', sa.Integer(), nullable=True),
    sa.Column('ClinicID', sa.Integer(), nullable=False),
    sa.CheckConstraint('Percentage IS NULL OR (Percentage >= 0 AND Percentage <= 100)', name='check_physician_percentage'),
    sa.ForeignKeyConstraint(['ClinicID'], ['Clinic.ClinicID'], ),
    sa.ForeignKeyConstraint(['EmpID'], ['ClinicPersonnel.EmpID'], ),
    sa.ForeignKeyConstraint(['OwnerID'], ['Owner.OwnerID'], ),
    sa.PrimaryKeyConstraint('EmpID')
    )
    op.create_table('Surgeon',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('ContractLength', sa.Integer(), nullable=False),
    sa.Column('ContractType', sa.String(length=50), nullable=False),
    sa.Column('Specialty', sa.String(length=100), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['EmpID'], ['ClinicPersonnel.EmpID'], ),
    sa.PrimaryKeyConstraint('EmpID')
    )
    op.create_table('NurseSkill',
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('SkillCode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['EmpID'], ['Nurse.EmpID'], ),
    sa.ForeignKeyConstraint(['SkillCode'], ['SurgerySkill.SkillCode'], ),
    sa.PrimaryKeyConstraint('EmpID', 'SkillCode')
    )
    op.create_table('Patient',
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('SSN', sa.String(length=20), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('Phone', sa.String(length=20), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=False),
    sa.Column('Address', sa.Text(), nullable=False),
    sa.Column('BloodType', sa.String(length=5), nullable=True),
    sa.Column('HDL', sa.Float(), nullable=True),
    sa.Column('LDL', sa.Float(), nullable=True),
    sa.Column('Triglyceride', sa.Float(), nullable=True),
    sa.Column('BloodSugar', sa.Float(), nullable=True),
    sa.Column('AllergyCode', sa.String(length=20), nullable=True),
    sa.Column('IsInpatient', sa.Boolean(), nullable=True),
    sa.Column('IsEmployee', sa.Boolean(), nullable=True),
    sa.Column('EmpID', sa.Integer(), nullable=True),
    sa.Column('PrimaryPhysicianID', sa.Integer(), nullable=False),
    sa.Column('HeartRiskLevel', sa.Enum('NONE', 'LOW', 'MODERATE', 'HIGH', name='heartrisk'), nullable=True),
    sa.ForeignKeyConstraint(['AllergyCode'], ['Allergy.AllergyCode'], ),
    sa.ForeignKeyConstraint(['EmpID'], ['ClinicPersonnel.EmpID'], ),
    sa.ForeignKeyConstraint(['PrimaryPhysicianID'], ['Physician.EmpID'], ),
    sa.PrimaryKeyConstraint('PatientID'),
    sa.UniqueConstraint('SSN')
    )
    op.create_table('Consultation',
    sa.Column('ConsultationID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('ConsultationDate', sa.Date(), nullable=False),
    sa.Column('Notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['EmpID'], ['Physician.EmpID'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.PrimaryKeyConstraint('ConsultationID')
    )
    op.create_table('Diagnosis',
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('ConsultationDate', sa.Date(), nullable=False),
    sa.Column('IllnessCode', sa.String(length=20), nullable=False),
    sa.Column('AllergyCode', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['AllergyCode'], ['Allergy.AllergyCode'], ),
    sa.ForeignKeyConstraint(['EmpID'], ['Physician.EmpID'], ),
    sa.ForeignKeyConstraint(['IllnessCode'], ['Illness.IllnessCode'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.PrimaryKeyConstraint('PatientID', 'EmpID', 'ConsultationDate')
    )
    op.create_table('Inpatient',
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('NursingUnits', sa.String(length=100), nullable=True),
    sa.Column('PatientRoomID', sa.Integer(), nullable=False),
    sa.Column('BedLabel', sa.Enum('A', 'B', name='bedlabel'), nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=True),
    sa.Column('AdmissionDate', sa.Date(), nullable=False),
    sa.CheckConstraint('NursingUnits >= 1 AND NursingUnits <= 7', name='check_nursing_units'),
    sa.ForeignKeyConstraint(['EmpID'], ['Nurse.EmpID'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.ForeignKeyConstraint(['PatientRoomID', 'BedLabel'], ['Bed.PatientRoomID', 'Bed.BedLabel'], name='fk_bed_inpatient'),
    sa.PrimaryKeyConstraint('PatientID', 'PatientRoomID', 'BedLabel')
    )
    op.create_table('Prescription',
    sa.Column('PrescriptionID', sa.Integer(), nullable=False),
    sa.Column('Dosage', sa.String(length=100), nullable=False),
    sa.Column('Frequency', sa.String(length=100), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('MedicationCode', sa.String(length=20), nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EmpID'], ['Physician.EmpID'], ),
    sa.ForeignKeyConstraint(['MedicationCode'], ['Medication.MedicationCode'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.PrimaryKeyConstraint('PrescriptionID'),
    sa.UniqueConstraint('PatientID', 'MedicationCode', name='unique_patient_medication')
    )
    op.create_table('SurgerySchedule',
    sa.Column('ScheduleID', sa.Integer(), nullable=False),
    sa.Column('PatientID', sa.Integer(), nullable=False),
    sa.Column('EmpID', sa.Integer(), nullable=False),
    sa.Column('Date', sa.Date(), nullable=False),
    sa.Column('SurgeryCode', sa.String(length=20), nullable=False),
    sa.Column('OpRoomID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['EmpID'], ['Surgeon.EmpID'], ),
    sa.ForeignKeyConstraint(['OpRoomID'], ['OperatingRoom.OpRoomID'], ),
    sa.ForeignKeyConstraint(['PatientID'], ['Patient.PatientID'], ),
    sa.ForeignKeyConstraint(['SurgeryCode'], ['SurgeryType.SurgeryCode'], ),
    sa.PrimaryKeyConstraint('ScheduleID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SurgerySchedule')
    op.drop_table('Prescription')
    op.drop_table('Inpatient')
    op.drop_table('Diagnosis')
    op.drop_table('Consultation')
    op.drop_table('Patient')
    op.drop_table('NurseSkill')
    op.drop_table('Surgeon')
    op.drop_table('Physician')
    op.drop_table('Nurse')
    op.drop_table('SurgerySkill')
    op.drop_table('MedicalCorporation')
    op.drop_table('DrugInteraction')
    op.drop_table('ClinicPersonnel')
    op.drop_table('SurgeryType')
    op.drop_table('Owner')
    op.drop_table('OperatingRoom')
    op.drop_table('Medication')
    op.drop_table('Illness')
    op.drop_table('Clinic')
    op.drop_table('Bed')
    op.drop_table('Allergy')
    # ### end Alembic commands ###
